### ISSUE TITLE
[バグ] 曲決定後の ScreenPlayerOptions 画面での譜面難易度について

### ISSUE THREAD

**Issue by kr4kp0t** [waiei/waiei2_bug#4]
使用バージョン: アルファテスト 20150426
StepMania バージョン: 5.0.7

はじめまして。お世話になります。
VERSUS プレイでゲームをスタートし、1P・2P ともそれぞれ別の難易度を選択、曲を決定後
プレイヤーオプションに入りますと難易度の項目のカーソルが1P側の難易度に固定されます。
また、ここでのカーソルも 1P・2P 別々に選択ができません。

そこで、大変僭越ながらスクリプトを拝見させていただきましたところ、
Scripts フォルダ内 90 waieiPrefs.lua 内の UserPlayDifficulty() 関数の
OneChoiceForAllPlayers が true になっている事が原因かと思われます。
(1493 行目)
こちらを false に変更しましたところ、別々に選択が可能となりましたので、
ご報告させていただきました。

0408追記:
プレイヤーオプションで難易度を変更、曲をプレイした後
曲選択画面の際に選択した難易度が反映されていませんでした。
上記ファイル内の SaveSelections 関数内の最後 (1555 行目付近) に
GAMESTATE:SetPreferredDifficulty(pn,curDif);
を加えると反映されるかと思います。

ご確認のほどよろしくお願い致します。ありがとうございました。

**Comment by waiei** [comment]
確認しました、次期バージョンで修正します。

**Comment by waiei** [comment]
8月30日バージョンで修正しました。
報告ありがとうございました。
